DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR,
    CONTENTS VARCHAR,
    WRITER VARCHAR );

INSERT INTO BOARD (TITLE, CONTENTS, WRITER) VALUES ('1 DB 제목 입니다.', '1 DB 콘텐츠 입니다.', '1 DB 작성자 입니다.');
INSERT INTO BOARD (TITLE, CONTENTS, WRITER) VALUES ('2 DB 제목 입니다.', '2 DB 콘텐츠 입니다.', '2 DB 작성자 입니다.');
INSERT INTO BOARD (TITLE, CONTENTS, WRITER) VALUES ('3 DB 제목 입니다.', '3 DB 콘텐츠 입니다.', '3 DB 작성자 입니다.');
